//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace __NAMESPACE__.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("__NAMESPACE__.Domain.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record was created successfully.
        /// </summary>
        internal static string CreateSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CustomMessage}.
        /// </summary>
        internal static string CustomValidationMessage {
            get {
                return ResourceManager.GetString("CustomValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CustomMessage.
        /// </summary>
        internal static string CustomValidationMessageArgument {
            get {
                return ResourceManager.GetString("CustomValidationMessageArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record to delete was not found.
        /// </summary>
        internal static string DeleteRecordNotFound {
            get {
                return ResourceManager.GetString("DeleteRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The DELETE statement conflicted with the REFERENCE constraint.
        /// </summary>
        internal static string DeleteReferenceError {
            get {
                return ResourceManager.GetString("DeleteReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record cannot be deleted because it has related records.
        /// </summary>
        internal static string DeleteReferenceMessage {
            get {
                return ResourceManager.GetString("DeleteReferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record was deleted successfully.
        /// </summary>
        internal static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A record with the same key already exists.
        /// </summary>
        internal static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} have an invalid email format.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must have {1} characters.
        /// </summary>
        internal static string FieldLength {
            get {
                return ResourceManager.GetString("FieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must have at most {1} characters.
        /// </summary>
        internal static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must have at least {1} characters.
        /// </summary>
        internal static string FieldMinLength {
            get {
                return ResourceManager.GetString("FieldMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} is required.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record was not found.
        /// </summary>
        internal static string GetRecordNotFound {
            get {
                return ResourceManager.GetString("GetRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The identifier is required.
        /// </summary>
        internal static string IdentifierRequired {
            get {
                return ResourceManager.GetString("IdentifierRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information to process is required.
        /// </summary>
        internal static string InformationRequired {
            get {
                return ResourceManager.GetString("InformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page Number.
        /// </summary>
        internal static string PageField {
            get {
                return ResourceManager.GetString("PageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page number must be greater than zero.
        /// </summary>
        internal static string PageFieldMinValue {
            get {
                return ResourceManager.GetString("PageFieldMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page Size.
        /// </summary>
        internal static string PageSizeField {
            get {
                return ResourceManager.GetString("PageSizeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page size must have at most 1000.
        /// </summary>
        internal static string PageSizeFieldMaxValue {
            get {
                return ResourceManager.GetString("PageSizeFieldMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page size must be greater than zero.
        /// </summary>
        internal static string PageSizeFieldMinValue {
            get {
                return ResourceManager.GetString("PageSizeFieldMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search parameters are required.
        /// </summary>
        internal static string SearchInformationRequired {
            get {
                return ResourceManager.GetString("SearchInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paging parameters are required.
        /// </summary>
        internal static string SearchPageInformationRequired {
            get {
                return ResourceManager.GetString("SearchPageInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort directions must be only &apos;asc&apos; or &apos;desc&apos;.
        /// </summary>
        internal static string SortDirectionNotValid {
            get {
                return ResourceManager.GetString("SortDirectionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record to update was not found.
        /// </summary>
        internal static string UpdateRecordNotFound {
            get {
                return ResourceManager.GetString("UpdateRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The record was updated successfully.
        /// </summary>
        internal static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
    }
}
