trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

variables:
  buildConfiguration: "Release"
  solution: "__NAMESPACE__.sln"
  apiProject: "__NAMESPACE__.Apis/__NAMESPACE__.Apis.csproj"
  publishDir: "$(Build.ArtifactStagingDirectory)/publish"
  ApiOptions.Version: "$(Build.BuildNumber)"

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build solution
        pool:
          name: Default
          vmImage: "ubuntu-latest"
        steps:
        - template: azure-pipelines.build.yml

  - stage: Dev
    displayName: Development
    dependsOn: Build
    variables:
      - group: Variables.Dev
      - group: Variables.Common
    jobs:
      - deployment: Deployment
        displayName: Deployment (Dev)
        environment: Dev
        pool:
          name: Default
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
              - template: azure-pipelines.deploy.yml

  - stage: Test
    displayName: Test
    dependsOn: Dev
    variables:
      - group: Variables.Test
      - group: Variables.Common
    jobs:
      - deployment: Deployment
        displayName: Deployment (Test)
        environment: Test
        pool:
          name: Default
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
              - template: azure-pipelines.deploy.yml

  - stage: Stage
    displayName: Stage
    dependsOn: Test
    variables:
      - group: Variables.Stage
      - group: Variables.Common
    jobs:
      - deployment: Deployment
        displayName: Deployment (Stage)
        environment: Stage
        pool:
          name: Default
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
              - template: azure-pipelines.deploy.yml

  - stage: Prod
    displayName: Prod
    dependsOn: Stage
    variables:
      - group: Variables.Prod
      - group: Variables.Common
    jobs:
      - deployment: Deployment
        displayName: Deployment (Prod)
        environment: Prod
        pool:
          name: Default
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
              - template: azure-pipelines.deploy.yml
